ALTER TABLE public.stores
ADD COLUMN IF NOT EXISTS light_primary TEXT,
ADD COLUMN IF NOT EXISTS dark_primary TEXT,
ADD COLUMN IF NOT EXISTS secondary_color TEXT,
ADD COLUMN IF NOT EXISTS body_bg TEXT,
ADD COLUMN IF NOT EXISTS success_color TEXT,
ADD COLUMN IF NOT EXISTS info_color TEXT,
ADD COLUMN IF NOT EXISTS warning_color TEXT,
ADD COLUMN IF NOT EXISTS danger_color TEXT;
